### ISSUE TITLE
No answer from server HEARBEAT ACK

### ISSUE THREAD

**Issue by wadx** [Aidoboy/discordpp#7]
Client seems sending HEARTBEATs right way, but server never answers, and after some time disconnect client.

**Comment by Aidoboy** [comment]
Oh, is that what's happening? Hrm. Maybe they changed how to send heartbeats? Busy right now, but I'll try to look into it when I have a chance. I may not need to switch to Beast. I still want to at some point though, I could use just Beast instead of Websocket++ & CurlPP.

**Comment by Cleroth** [comment]
Does thaht mean this is currently unusable?

**Comment by Aidoboy** [comment]
Yes, it does. I'm currently refactoring it, but stuff had been hectic.

**Comment by Cleroth** [comment]
Understandable, but may want to update the README with a warning or something...

**Comment by hiddos** [comment]
Unless I'm mistaken, #9 fixed this

**Comment by Aidoboy** [comment]
Yup looking like it.
